mlp:mlp.cpp Q1tongji
	g++ mlp.cpp -o mlp -std=c++11 -lpthread -fpermissive
Q1tongji:Q1tongji.cpp rcomb
	g++ Q1tongji.cpp -o tongji -std=c++11 -lpthread -fpermissive
rcomb:rcomb.cpp trainparallel
	g++ rcomb.cpp -o rcomb -std=c++11 -lpthread -fpermissive
trainparallel:trainparallel.cpp 
	g++ trainparallel.cpp -o trainparallel -std=c++11 -lpthread -fpermissive
GetResult:GetResult.cpp maxmin GetResult
	g++ GetResult.cpp -o GetResult -std=c++11 -lpthread -fpermissive
maxmin:maxmin.cpp
	g++ maxmin.cpp -o maxmin -std=c++11 -lpthread -fpermissive